services:
  - type: web
    name: exam-score-predictor
    env: python
    python:
      version: 3.9.13
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
